[package]
name = "zod"
version = "0.1.0"
authors = ["yml <yuemenglong@126.com>"]
build = "build.rs"

[dependencies]
glob = "*"

[build-dependencies.orm]
path = "../orm"

[dependencies.orm]
path = "../orm"
